# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x06mapper\"\"\n\rMapperRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\r\n\x0bMapperReply2H\n\x06Mapper\x12>\n\x10SendFileLocation\x12\x15.mapper.MapperRequest\x1a\x13.mapper.MapperReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPPERREQUEST._serialized_start=25
  _MAPPERREQUEST._serialized_end=59
  _MAPPERREPLY._serialized_start=61
  _MAPPERREPLY._serialized_end=74
  _MAPPER._serialized_start=76
  _MAPPER._serialized_end=148
# @@protoc_insertion_point(module_scope)
